### ISSUE TITLE
Compatibility to rancher server networking

### ISSUE THREAD

**Issue by pwFoo** [lucaslorentz/caddy-docker-proxy#1]
I found your reverse proxy plugin and could be move from my own custom to your solution.
But to be compatible with [rancher server](https://github.com/rancher/rancher) the ip address have to be read from a custom label.
```
            "IpcMode": "",
                "io.rancher.cni.network": "ipsec",
                "io.rancher.container.ip": "10.42.155.12/16",
```

Would it possible to add this custom value or overwrite the ip variable by this one optional?

**Comment by lucaslorentz** [comment]
I'm not familiar with rancher internals.
This plugin reads label from docker swarm services and use them to generate caddyfile configuration.
Does rancher use docker swarm services?
Is the label `io.rancher.container.ip` available at **service** level or at **container** level?

How the ip should be used? As a target for caddy proxy directive? Like:
```
proxy / 10.42.155.12 {
    transparent
}
```

**Comment by pwFoo** [comment]
Rancher server uses cattle by default and the label should be container level instead of the default docker container ip address field.

Rancher optionally works with swarm and kubernetes too.

So your plugin isn't similiar to jwilder docker-gen which read container ip and generate a RevProxy / LB?

Ich converted jwilder RevProxy to Caddy and generate a caddyfile that way. It works with single and multiple (load balanced) backends. Each backend is identified by custom ip label.

May IT help if I post the docker-gen template here?

**Comment by pwFoo** [comment]
Yes, the ip(s) used as target for caddy proxy directive.

**Comment by lucaslorentz** [comment]
> So your plugin isn't similiar to jwilder docker-gen which read container ip and generate a RevProxy / LB?

While jwilder docker-gen gets metadata about every container and use their ips as back-end.
This plugin gets metadata about docker swarm services and use those services dns name as caddy back-end.
The generated configuration looks like:
```
some-domain.com {
  proxy / myservicename {
    transparent
  }
}
```
So, with this plugin, caddy proxies some domain to a docker swarm service, and docker swarm is responsible for load balancing service traffic to all containers.

**Possible changes to this plugin**
Currently, this plugins works well with multi node clusters. Mainly because it is aware and leverages swarm orchestration.

We could change this plugin to also support metadata from containers, that would make it less swarm specific.

But my understanding is that any automatic reverse-proxy should be aware about the orchestrator (swarm, kubernetes, cattle) to be able to get information about every container running on every node.

I suppose docker-gen only gets information about containers running on the same node it is running, right?

**Other possibilities**
- Change rancher to use swarm orchestrator and check if changes to this plugin are still necessary.
- Fork this plugin and create something for rancher/cattle, it probably exposes information about nodes/services/containers on some api.
- Try traefik, it seems to support rancher.

**Comment by pwFoo** [comment]
My custom RevProxy / LB used docker-gen and works at host base, but rancher LB  use the service name too.

http://rancher.com/docs/rancher/v1.2/en/cattle/adding-load-balancers/

So maybe it's compatible... Rancher-compose is based on docker-compose and compose syntax with services is supported. 

I'll have to test it.

**Comment by pwFoo** [comment]
Rancher Labels
http://rancher.com/docs/rancher/v1.2/en/cattle/labels/

**Comment by pwFoo** [comment]
Information about rancher services
http://rancher.com/docs/rancher/v1.6/en/cattle/adding-services/

**Comment by lucaslorentz** [comment]
Maybe if this project support reverse proxying to containers it would work with rancher.

There are some benefits of adding that feature, like being able to use sticky sessions and load balancing from caddy.

**Comment by lucaslorentz** [comment]
Closing this issue as Rancher is not the focus.
