### ISSUE TITLE
How to proxy tcp traffic (non-http)?

### ISSUE THREAD

**Issue by wsw70** [lucaslorentz/caddy-docker-proxy#101]
_First of all: thank you for your work. I decided to get rid of `traefik` because of its horrendous documentation and support and miraculously stumbled upon your fantastic container which exactly does what I needed. Thank you._

While the proxification of HTTP works great, I am wondering whether it is possible to proxify non-HTTP ones?

Specifically I have an MQTT broker in a container (mosquitto) which internally exposes port `1883` . I would like to configure `caddy` to proxify traffic directed to, say, port `2883` (exposed by the `caddy` configuration in `docker-compose.yaml` to the MQTT broker one (`1883`).

I believe that the "traditional" way to do this in `caddy` is to use the [`net` plugin](https://github.com/pieterlouw/caddy-net/blob/master/README.md).

Is this something which is possible to do with your docker image?

**Comment by lucaslorentz** [comment]
Actually I think we already support this.
The label to caddyfile conversion is quite flexible.
But you would need a separate caddy instance running *net* server instead of http.
I wonder if that's what you want, because you can achieve the same with Swarm services.

**Comment by lucaslorentz** [comment]
Caddy doesn't support running multiple server types simultaneously.

**Comment by wsw70** [comment]
> I wonder if that's what you want, because you can achieve the same with Swarm services.

Thank you. I have never used Swarm services (since I run my docker containers on one host). Would you mind elaborating a bit on how I should approach this? (the forwarding of raw tcp traffic on Swarm as opposed to having a second instance of caddy)

**Comment by lucaslorentz** [comment]
I will try to explain the options I think you have.

I think option 1 and 2 replaces **caddy net** for you. Please let me know if **caddy net** has additional features that you need.

They increase in complexity, so if option 1 is enough for you, I would go for it.

**1 - Bind host port 2833 to your MQTT container port 1833**
You can expose any docker container by binding a the host port to a container port. With that you can expose any http container, or even your MQTT container. You can bind host port 2833 to container port 1883.

**2 -  Create a docker swarm service and bind host port 2833 to service port 1833**
Some people needs replicas for their containers, either to increase performance or for redundancy. Docker swarm mode is a container orchestrator with features that supports that use case. One of the concepts in docker swarm is **service**, which orchestrate replicas of the same container and also creates a virtual IP that load balance network traffic to all replicas. It is possible to bind host ports to service vip as well.

**3 - Use additional load balancers/reverse proxy like caddy, nginx, haproxy, traefik**
But docker swarm service is a layer 3 balancer, it doesn't know about protocol layer: HTTP or MQTT. Because of that it cannot provide all features a layer 7 (protocol aware) load balancer/reverse proxy can provide.

So, If you need one of the items for HTTP protocol:
- routing, enabling you to expose multiple websites on the same host and port
- shield your http application with additional or better http implementation
- load balancer aware of http protocol, with cookie based sticky session for example
Then caddy, traefik, nginx, envoy and many others come into play.

Same might happen for other other protocols, you might find some MQTT aware load balancer as well.

**Comment by wsw70** [comment]
> Bind host port 2833 to your MQTT container port 1833

This is what I initially had. In the course of my move to docker (from systemd-nspawn) I was looking to reverse proxy everything (this is what I will be doing with your caddy-docker-proxy).

But you are correct: in this case I will bind the container port to the host and go the easy way.

Thanks again for your great work and your advice.
