### ISSUE TITLE
Service <id> and caddy are not in same network

### ISSUE THREAD

**Issue by theneedyguy** [lucaslorentz/caddy-docker-proxy#104]
Hi I am using your example docker-compose file for my docker swarm to test if the plugin works. But it is not working. I get this message in the caddy logs that the service is not in the same network as caddy. Why is your example docker-compose file working but mine isn't?

`# Service jwqf700wuqo6wvyia7m477s25 and caddy are not in same network`

**Comment by lucaslorentz** [comment]
Do you use multiple compose files?

Keep in mind that if you do not explicitly define the networks in a compose file, each deployed compose file will have a different default network.

Are you using `docker stack deploy` or `docker-compose`?

**Comment by theneedyguy** [comment]
Yes, I am following the exact steps and use your exact compose file. (With only changing the domain label to my domain.)

**Comment by lucaslorentz** [comment]
I tested both examples again, with docker stack and docker-compose and didn't face that issue.

Can you please do a docker inspect on your service and also on caddy container, and paste JSONs here?

**Comment by kidcuauh** [comment]
Caddy swarm use overlay networks and that's great if we want to scale our proxy, you could face issues when your proxy isn't in the same network as your services or containers which could happen when your stack has its own swarm network, you will be okay if you are declaring inside your yaml new containers or services but external standalone containers labels will not be working and therefore automation could be killed) so if you want to implement standalone container labels your containers or services need to be on the same network as the proxy, here are some highlights:

1. Create an overlay --attachable network.
2. Declare in your proxy .yaml file this network as external.
3. Assign new containers deployed to this overlay network with --net in docker run execution.
4. Talk to your proxy by docker labels for each container deployed. (Here I edit my Dockerfile labels before to do an image build for my specific project needs).

Now your proxy will communicate internally with containers, it means that standalone containers don't need published ports but EXPOSE in Dockerfiles, I have 80-80, 443:443 and 2015:2015 as port open in my proxy .yaml file. Your proxy will be updating all your new standalone container updates based in LABELS since they can be viewed on the same network.

I have done some tests and it works like a charm, hope it helps. @theneedyguy @lucaslorentz

**Comment by lucaslorentz** [comment]
I'm not sure that's the problem @theneedyguy faced though. Because he mentioned he used one of [those](https://github.com/lucaslorentz/caddy-docker-proxy/tree/master/examples) compose files, and they all have the proxy and containers in same yaml, thus same network.

@kidcuauh Thanks for sharing instructions. That's how I do on my production environments, I create a network separately, and reference it on several compose files.

**Comment by Erman2** [comment]
Hello,

I'm having similar  issue. I have multple docker-compose files with services. Each  But I don't want to put all containers on the same network. Is there any workdaround ? I was thinking that instead of the servicename the 127.0.0.1 address could be used.

**Comment by piaste** [comment]
@lucaslorentz  Thanks for the recently committed 'skip network validation' option. I was kind of tearing my hair out because it would fail literally at random: scale 5-10 instances of the service, 1-2 would work properly and the rest would fail to find the network, despite all of them being attached. I set the new environment flag and updated to use the `ci:alpine` image and now they all run correctly. Hope it lands a stable release soon.

**Comment by lucaslorentz** [comment]
@piaste 
Done, version 0.3.3 is out.
That's the only change from 0.3.2, so it should be stable.

**Comment by lucaslorentz** [comment]
Closing the issue because there is a workaround to the problem now.
https://github.com/lucaslorentz/caddy-docker-proxy/pull/127
