### ISSUE TITLE
Implement Caddyplug

### ISSUE THREAD

**Issue by unixfox** [lucaslorentz/caddy-docker-proxy#105]
Currently, for adding plugins to `caddy-docker-proxy` we have to fork the repository then add the plugins and finally build the Docker image.

I found about [caddyplug](https://github.com/abiosoft/caddyplug) which is a program designed to quickly add plugins to the caddy binary.

I would love to see an integration of that program in the `caddy-docker-proxy` Docker image. Ideally we would just have to specify an environment variable with the plugins we want and it's done.

**Comment by lucaslorentz** [comment]
That seems interesting.

Even if we adopt caddyplug, you would still need to build your docker image right? Or would you rely on caddyplug to download and compile plugins every time a container starts?

**Comment by unixfox** [comment]
I see three possibilities:
- Build the binary only at the first start and cache it a volume until the plugins list is changed.
- Build the binary every time the container starts and cache [the go modules cache](https://stackoverflow.com/a/52127364) to accelerate the build. That may take a while depending on the resources given for the container.
- Use caddyplug to just replace the need to add plugins in the [main.go](https://github.com/lucaslorentz/caddy-docker-proxy/blob/master/main.go) file but that would still require cloning the repo if a user wants to add plugins without doing a PR in the [initial Github repository](https://github.com/lucaslorentz/caddy-docker-proxy/).

**Comment by lucaslorentz** [comment]
Which of those three possibilities are supported by https://hub.docker.com/r/abiosoft/caddy/ ?
I wonder how we can leverage abiosoft work instead of duplicating efforts.
Maybe one of our images could be based on abiosoft/caddy, and we install caddy-docker-proxy plugin in it and redistribute the image.
Any suggestions?

**Comment by unixfox** [comment]
None of them if it implies using `caddyplug` because it builds its own binary.

**Comment by lucaslorentz** [comment]
AFAIK

image tag abiosoft/caddy:plugin was using caddyplug to build caddy and plugins, but it is not up-to-date, that is close to approaches #1 and #2 that you described

image tag abiosoft/caddy:builder uses caddyplug only as a plugin registry and builds caddy without modules, that is close to approach #3 that you described
You can do an up to date image with commands:
```
docker build --build-arg plugins=git,docker github.com/abiosoft/caddy-docker.git
```

@abiosoft any important reason to stop with abiosoft/caddy:plugin experiment? Any plans to resume it?

**Comment by abiosoft** [comment]
The only way I know to avoid rebuilding Caddy due to plugin changes is by leveraging Go plugins. However, Go plugins has two main limitations.
* inability to build with `CGO_ENABLED=0`. This affects portability. e.g. image built on Alpine to compatible wouldn't run on Debian and vice versa.
* both the binary and all plugins must be built with exactly same Go version to be compatible.

**Comment by francislavoie** [comment]
I think this can be closed @lucaslorentz, I don't think caddyplug will make a comeback for v2. Best to just have people build a Caddy image themselves with either `xcaddy` or the `builder` official docker image.
