### ISSUE TITLE
[Feature request] validate each service independently.

### ISSUE THREAD

**Issue by mxrlkn** [lucaslorentz/caddy-docker-proxy#120]
### Problem

If a service is configured incorrectly, then caddy will keep running with the last working configuration (via USR1) and log the error (good).

Mispelling "websocket" for example

```
labels:
  caddy.targetport: 8080
  caddy.address: example.com
  caddy.proxy.websockett: ""
```

`CaddyFile error: :40 - Error during parsing: unknown property 'websockett'`

But if that error goes unnoticed, and the caddy container restarts, caddy won't run because it starts with a clean state and then can't fallback with USR1.

### Possible solution

For each service, create a temporary caddyfile (in memory I imagine), run caddy with the validate flag, log the errors if there is any, and then only stitch together the services that works. Now a misconfigured service won't take all the other services down.

Because you can apply a global caddyfile with caddy-docker-proxy, that needs to be inserted as well for each service when it validates.

I had a discussion about this over on the caddy forum, and gamalan came up with this idea which I think would be really great to implement.
https://caddy.community/t/fault-tolerance-docker-clustering/6097

**Comment by lucaslorentz** [comment]
Interesting discussion and solution!

### Comments about the proposed solution

I think it would be a bit problematic to isolate and validate caddyfile per service/container because:
- There might be dependencies between configuration from different services/containers. Like a snippet declared in one service/container and used in another service/container.
- We merge configuration from service and containers that share same website addresses.

Therefore, it might be better to do it after the full caddyfile is generated. Then we break it down into websites and validate each website configuration, removing invalid websites from caddyfile.

Considering this might grow into the following features:
- If some website have invalid configuration, it shouldn't block valid websites from being served.
- If some website have invalid directive, that directive should be ignored but others should be applied to that website

I think it might be better to implement it in caddy repository. @mholt what do you think?

**Caveat**
If I have a working service/container being served.
Then I add a label caddy.proxy.websockett.
All other websites will continue being served, but the wrongly configured service/container will stop being served. Maybe it would be better to serve this website with the previous configuration instead of stopping it.

### Alternative solution
Always save valid caddyfile in filesystem.
When container restart and the new configuration is wrong we fallback to saved caddyfile.
We could save it in same folder where certificates are saved /root/.caddy, because that's usually persistent volume shared across all caddy containers.

This solution is simpler and solves the caveat from the other solution.

**Caveat**
After you do a wrong configuration. Caddyfiles updates are blocked until you fix that mistake.

@mxrlkn What do you think?

**Comment by mxrlkn** [comment]
### Proposed solution

> There might be dependencies between configuration from different services/containers.

I didn't know that was possible. I think it's kind of an anti-pattern to do that in this context. But I get the issue.

> We merge configuration from service and containers that share same website addresses

I guess the validation would need to happen after the merge. And then if it doesn't validate properly, both services go down, if possible.

#### Caveat

I don't think this is a problem. I'd almost rather have it fail instantly now than later when I don't expect it to.

### Alternative solution

This sounds to be the easiest solution. I currently build my own docker image with the global caddyfile COPY'ed in so I don't have to mount anything. But I guess mounting this other temporary caddyfile wouldn't be that bad. In my scenario caddy-docker-proxy would run on several servers with a load balancer in front. I don't think that would cause issues in that case.

---

If it's the alternative solution, I think a webhook environment variable would be a great addition that fires when a caddyfile error happens. Then you could get notified in slack or something so you're not unaware of the error. And you wouldn't need to build some kind of log monitoring around it.

WEBHOOK_URL=https://example.com/incoming_webhook

---

I still like the idea of the first solution the most. But I can't see how you can have dependencies (snippets etc.) working across services/containers, with the new validation. You'd have to not support that feature at all I think. That would be fine for me, but I don't know how many use that feature.

I think the alternative solution is an okay compromise though.

**Comment by mholt** [comment]
As an aside -- but related to this -- I'd be interested in having your guys' feedback on Caddy 2's REST API, which is the primary method for applying configuration changes. I suppose it could help with at least some layer of this problem.

**Comment by lucaslorentz** [comment]
Feature is available in master. You can test it using CI docker images.

Use cli option `-docker-process-caddyfile` or enviroment variable  `CADDY_DOCKER_PROCESS_CADDYFILE` to enable it.

Please provide feedback if it is working as expected.

It will be officially released and added to README on version v0.4.0.

**Comment by mxrlkn** [comment]
Just did a quick test, and it works perfectly!

So It looks like you went with the proposed solution. How did you solve the dependency problem across services/containers?

**Comment by lucaslorentz** [comment]
Thanks for the feedback.

The proposed solution have a good behavior, and doesn't depend on persistent volumes.
It turn's out it was not complex to develop as well.

I process the caddyfile after it is generated, that avoids problems with dependencies between services/containers.

Caddy package already provided all parsing/validation logic I needed. The main thing I wrote is serialization back to Caddyfile.

Implementation:
https://github.com/lucaslorentz/caddy-docker-proxy/blob/master/plugin/caddyfileprocessor.go
Tests:
https://github.com/lucaslorentz/caddy-docker-proxy/blob/master/plugin/caddyfileprocessor_test.go
