### ISSUE TITLE
Subject is missing in internal tls issued certificates

### ISSUE THREAD

**Issue by aduzsardi** [lucaslorentz/caddy-docker-proxy#162]
I opened the same issue on caddy's github page , they say this is fixed in master but as far as i know the alpine-ci image is built from master and it did not fix it for me

Any ideas what could it be ?

Related issues
https://github.com/caddyserver/caddy/issues/3558
https://github.com/caddyserver/caddy/issues/3535

**Comment by lucaslorentz** [comment]
Actually CI images are not built from Caddy master.
It uses caddy-docker-proxy master + latest caddy release.

That's because we need something stable to build on top of. If caddy master branch has broken code for some days, it shouldn't impact this project builds.

You could build it by yourself using the instructions here: https://github.com/lucaslorentz/caddy-docker-proxy#building-it
caddy docker builder makes it simpler to build a docker image.

**Comment by aduzsardi** [comment]
Thank you, i'll try to build it and see how it goes

**Comment by aduzsardi** [comment]
well, i built it but seems to fix the issue with Chrome/Chromium but the subject is still missing from the issued certificate

```
caddy version
v2.1.2-0.20200709055615-735c86658d05 h1:LUsuayyEoQA3xE8t5zUIr/1WHS19/V8V9KxGv2YPjkY=
```

Thank you!

**Comment by aduzsardi** [comment]
it's a caddy thing and it won't be fixed , they say this is how it suppose to be
