### ISSUE TITLE
distributed example doesn't mention the data volume

### ISSUE THREAD

**Issue by SvenDowideit** [lucaslorentz/caddy-docker-proxy#177]
https://github.com/lucaslorentz/caddy-docker-proxy/blob/master/examples/distributed.yaml#L5

whereas the standalone one mentions it very explicitly https://github.com/lucaslorentz/caddy-docker-proxy/blob/master/examples/standalone.yaml#L11

I'm basically wondering - when I have 4 caddy-docker-proxy containers, who is doing the acme request, do they share it, and do they all store them

I'm presuming this isn't really in scope for your project, but I'm curious if this is something you already know the answer to :)

**Comment by lucaslorentz** [comment]
Hey, it coordinates the challenge solving between the instances and shares certificates.

From certmagic [README](https://github.com/caddyserver/certmagic):
> Distributed solving of all challenges (works behind load balancers)
   Highly efficient, coordinated management in a fleet
   Active locking
   Smart queueing

In order to use that feature, you must share the same volume across all instances. I'm not sure if that feature also works when you use different storages for certificates like consul. @francislavoie Do you know that?

Probably you can get more information in caddy forum as this feature comes from caddy core, not this plugin.

**Comment by SvenDowideit** [comment]
oh - seriously nice! I'm clearly struggling to read all the docs in the right order :)

**Comment by lucaslorentz** [comment]
No problem. I'm glad to answer questions that are within my knowledge.
It's a very nice feature!
Some http servers charge for cluster features like this one 😄
