### ISSUE TITLE
Caddy v2 unrecognized directive "push"

### ISSUE THREAD

**Issue by sp4ke** [lucaslorentz/caddy-docker-proxy#192]
Hi, I'm using caddy-docker-proxy v2.3.0 (also tried v2.2.0) and the "push" directive is unrecognized
```
 [ERROR]  Removing invalid block: Caddyfile:29: unrecognized directive: push
caddy    | moz.****.com {
caddy    |      push
caddy    |      reverse_proxy 192.168.16.*:****
caddy    | }

```

The *docker-compose* labels look like this:
```
labels:
  caddy: my.domain.tld
  caddy.push:
```

**Comment by francislavoie** [comment]
The `push` directive was just added in Caddy v2.2, so the CDP image needs to be updated to use the latest version of Caddy.

**Comment by sp4ke** [comment]
@francislavoie thanks for the quick answer, yes I also realized and was about to close/update my comment. 

Currently trying to manually build using the build script but it's failing right now with:
```
/go/pkg/mod/github.com/caddyserver/certmagic@v0.11.2/crypto.go:20:2: unknown import path "crypto/ed25519": cannot find module providing package crypto/ed25519
```

**Comment by francislavoie** [comment]
Try building with these steps:

https://github.com/docker-library/docs/tree/master/caddy#adding-custom-caddy-modules

Using `github.com/lucaslorentz/caddy-docker-proxy/plugin/v2` as the module path.

There's nothing special about the Docker image in this repo, it just runs `caddy docker-proxy` as the command instead of `caddy run`

**Comment by sp4ke** [comment]
@francislavoie thanks a lot it worked.

I modified a bit the example Dockerfile by appending the following:
```
ENTRYPOINT ["/usr/bin/caddy"]
CMD ["docker-proxy"]
```
