### ISSUE TITLE
Feature Request: Accessing Caddy API

### ISSUE THREAD

**Issue by suchwerk** [lucaslorentz/caddy-docker-proxy#221]
I would like to use the caddy api in addition to the docker labels. So it would be nice, if the controller would forward api requests to the servers. Also there has to be some config merging as the whole server config is overwritten with the config derived form the labels. In my use case i want to add/remove additional hosts dynamically. What do you think?

**Comment by francislavoie** [comment]
CDP is built on the idea of generating Caddyfile config from Docker labels. The Caddyfile is a config adapter that outputs JSON. It's also a one-way adapter, there's no way to get a Caddyfile back from a given JSON config.

Because of this, it's not viable to mix usage of JSON config or the API with usage of the Caddyfile. So if you need to use the API, this isn't the right tool for you.

**Comment by lucaslorentz** [comment]
As @francislavoie  mentioned. Merging JSON configuration would be quite challenging for CDP. Today we do all manipulation and merging in caddyfile format.

Did you consider connecting to docker API instead and manipulate docker configs or labels?

For example, if you create a docker config inside docker swarm via API and label it with caddy, its content will be merged and sent to all servers automatically. [example](https://github.com/lucaslorentz/caddy-docker-proxy/blob/master/examples/standalone.yaml#L10)

Maybe you can share more deatils about your use-case, which kind of settings you want to set via API?

**Comment by francislavoie** [comment]
Closing as resolved.
