### ISSUE TITLE
Maybe problem with self signed certificates?

### ISSUE THREAD

**Issue by pwFoo** [lucaslorentz/caddy-docker-proxy#271]
Hi,
I try to use caddy-docker-proxy with HTTP and HTTPS self signed and get a start error?
```
2021/07/01 10:51:29.948 WARN    pki.ca.local    installing root certificate (you might be prompted for password)        {"path": "storage:pki/authorities/local/root.crt"}
2021/07/01 10:51:29 Warning: "certutil" is not available, install "certutil" with "apt install libnss3-tools" or "yum install nss-tools" and try again
[...]
2021/07/01 10:51:29.950 ERROR   pki.ca.local    failed to install root certificate      {"error": "failed to execute tee: exit status 1", "certificate_file": "storage:pki/authorities/local/root.crt"}
```
Is there certutil missing in your docker image? Or how to solve that error?

Best Regards

**Comment by lucaslorentz** [comment]
I think that cert installation is just to improve local development experience.
It installs the certificate on your local machine, so when you open a caddy website in your browser it will trust it.
I don't think that makes sense in a docker image or a server, because that's not where your browser will be running.
So, you can just ignore this error, or maybe try to disable that feature.

**Comment by lucaslorentz** [comment]
This is the option to disable it:
https://caddyserver.com/docs/caddyfile/options#skip-install-trust

**Comment by lucaslorentz** [comment]
A label to disable it can be added to your caddy service/container, it would look like:
caddy.skip_install_trust: ""

**Comment by francislavoie** [comment]
That's correct - that warning is harmless. You can safely ignore it. It doesn't make too much sense to install the root certificate inside the container, it doesn't have any useful effect. The certificate needs to be installed probably on your host machine for it to be useful, but it's not possible for the Caddy inside the container to do that because it's isolated from anything outside it.

That global option to skip the install attempt was just added in v2.4.3 (or v2.4.2, I forget which) so you'll need the latest version for it.

You can find the root certificate at `/data/pki/authorities/local/root.crt` in the container, and you can install that certificate manually to your system's or browser's trust store manually to remove the trust warning when accessing your site. You can use Google to find instructions for your browser/OS of choice.

**Comment by pwFoo** [comment]
Thanks! Solved for me

**Comment by pwFoo** [comment]
> A label to disable it can be added to your caddy service/container, it would look like:
> caddy.skip_install_trust: ""

So it's possible to configure caddy-docker-proxy itself by container labels...? Or did I get it wrong?

**Comment by francislavoie** [comment]
That's a Caddyfile global option. See https://github.com/lucaslorentz/caddy-docker-proxy#sites-snippets-and-global-options. You can add labels to any container, including the CDP container itself.

**Comment by lucaslorentz** [comment]
That's right. In the end, you have full control of the generated Caddyfile.

To generate global options, all you have to do is omit the site name.

Example:
```
caddy: "localhost"
caddy. skip_install_trust: ""
```
Would generate:
```
localhost {
  skip_install_trust
}
```

But if you omit the first label, it will generate a global options block:
```
{
  skip_install_trust
}
```
