### ISSUE TITLE
caddy.basicauth cors headers not set

### ISSUE THREAD

**Issue by do-web** [lucaslorentz/caddy-docker-proxy#281]
I use this:

`
        caddy: exmaple.org
        caddy.reverse_proxy: "{{upstreams 80}}"
        caddy.basicauth.admin: xxxx
`

If i use basicauth the CORS headers are missing, If I remove the basic auth, CORS headers are there.
![Bildschirmfoto 2021-07-20 um 19 05 15](https://user-images.githubusercontent.com/862783/126369069-bf2d712b-a0aa-43f2-a4e4-be60dcb5918b.jpg)

**Comment by francislavoie** [comment]
There's not enough information here about what you're trying to do.

If this is an example of a request where you didn't pass valid credentials, then that's to be expected, because Caddy will throw an authentication error before `reverse_proxy` is even called.

Probably best to ask your usage questions on the [Caddy community forums](https://caddy.community). Don't forget to fill out the thread template so we can help you!

**Comment by do-web** [comment]
No the credentials are correct. Looks releated to https://github.com/caddyserver/caddy/issues/1568

How can i do something like this with the labels?

```
@basic_matcher {
        not method OPTIONS
}

basicauth @basic_matcher { ... }
```

**Comment by francislavoie** [comment]
Labels are a 1:1 map to the Caddyfile; yes you can do that. Looks like this, I think:

```
caddy.@skipauth: "not method OPTIONS"
caddy.basicauth: "@skipauth"
caddy.basicauth.admin: "hash"
```
