### ISSUE TITLE
Generator is using IP for only some configs?

### ISSUE THREAD

**Issue by OmgImAlexis** [lucaslorentz/caddy-docker-proxy#31]
Is there a reason the Caddyfile is now being updated with IP addresses whereas it use to have the container dns name?

All my other containers are like the portainer one.

```
homeassistant.domain.tld {
  proxy / 10.0.10.11:8123 {
    transparent
    websocket
  }
}
portainer.domain.tld {
  proxy / portainer:9000
}
```

**Comment by lucaslorentz** [comment]
If you use labels at container level, it will use container ip address.
If you use labels at service level, it will use the service dns name.

It is a very subtle difference on docker-compose file:
https://docs.docker.com/compose/compose-file/#labels-1

**Comment by pwFoo** [comment]
@lucaslorentz 
At the moment I have some problems with docker swarm dns resolution.

I don't know why, but after some time the swarm service container ip changes (restart, redeploy or what ever) and my service isn't reachable by swarm dns name anymore... I have to redeploy the service to get a new dns name and working container / service name resolution.
It looks like a bug for me...

So maybe it would be safer to use ip address(es) to proxy backends instead of swarm service / container dns names? 

Did You noticed some swarm dns issues / bugs with caddy docker proxy?

**Comment by lucaslorentz** [comment]
@pwFoo 
I had the same issue.
It seems to be a swarm issue with VIP load balancing.

We can workaround it by using `tasks.service` dns, instead of using service VIP.

I added some time ago this CLI option: **proxy-service-tasks** (Proxy to service tasks instead of VIP)

I've been using it for some time and it is much more stable.

Usage example:
```
command: -email email@example.com -agree=true -log stdout -proxy-service-tasks
```

**Comment by pwFoo** [comment]
At the moment I work with container labels and all works fine with container ip addresses (until backend and proxy is in the same network!).
But I'll try the `proxy-service-tasks` flag. Thanks!

For my custom service (docker-gen to get container hostname / dns) which have the above describled problems. Here I have to find my own solution to get working dns / ip with docker-gen.
