### ISSUE TITLE
How to use ports other than 80 and 443

### ISSUE THREAD

**Issue by jcm4atx** [lucaslorentz/caddy-docker-proxy#317]
I have searched and searched for an answer to this. I thought it'd be a more common problem.

On my machine ports 80 & 443 are already in use. If I stop Apache, this works just fine. But I need Apache to run. When I change to an unused port I get too many redirects. I'm trying to do something like this:

```
ports:
  - 8018:80
  - 8019:443
```

Maybe caddy-docker-proxy isn't intended to be used this way? Or I'm completely missing something.

**Comment by francislavoie** [comment]
If you want Automatic HTTPS, you _must_ use ports 80 and 443 so that the ACME challenges can succeed and get certificates from Let's Encrypt or ZeroSSL. You'll need to turn off whatever's using those ports to let Caddy use them.

Another option is to enable and use the ACME DNS challenge, which involves building Caddy with the appropriate plugin for your DNS provider so that Caddy can issue certs requiring ports 80 and 443 to be used. https://caddyserver.com/docs/automatic-https#dns-challenge

If you don't need HTTPS at all, then you can just use a site address like `:8080` in your Caddy config/labels and map that port to the host like `- 8080:8080`.

**Comment by jcm4atx** [comment]
Thank you for the additional information. Since Apache is handling my https, I'm going to work on that last option.

For the record this is what I'm trying to do: https://help.nextcloud.com/t/the-optimal-fastest-nextcloud-fpm-docker-setup-with-caddy-as-webserver-and-https-proxy/110515

**Comment by francislavoie** [comment]
That guide implies using Caddy for HTTPS. You can completely replace Apache with Caddy, and simplify your setup by only running a single web server.

**Comment by jcm4atx** [comment]
Thank you. I have the week off, I'll experiment. Apache has always been my go to web server, but if there's something better...
