### ISSUE TITLE
SSL_ERROR_INTERNAL_ERROR_ALERT for non-existing/unmapped subdomain

### ISSUE THREAD

**Issue by arminus** [lucaslorentz/caddy-docker-proxy#319]
Suppose my caddy config maps a couple of subdomains for xyc.com - is there some way to prevent the SSL_ERROR_INTERNAL_ERROR_ALERT for whatever.xyc.com - i.e. a default redirect or 404 page?

**Comment by francislavoie** [comment]
That error message is because the TLS handshake failed - Caddy didn't have a valid certificate it could use to serve that domain, so it couldn't complete the handshake.

The only way to get through that is by having Caddy issue a certificate for that subdomain. To do that, you can add another site and simply perform a redirect. You could add the labels to the `caddy-docker-proxy` service if it's just a one-off subdomain you're worried about.

To do this _in general_, for all subdomain, then you'd need a wildcard certificate. Getting one is more complicated, because you need to use the ACME DNS challenge to prove to the ACME issuers that you control the domain. https://caddyserver.com/docs/automatic-https#wildcard-certificates.

**Comment by arminus** [comment]
Thank you!
