### ISSUE TITLE
[Question] Proxy internal container traffic because of certificate problems

### ISSUE THREAD

**Issue by pwFoo** [lucaslorentz/caddy-docker-proxy#328]
Hi and a happy new year :) 

I use your as public reverse proxy and it works fine.

Now I have problems with self signed certificates with internal container connections (ldap container).
Would it possible to use the caddy proxy (maybe an second instance if needed?) to create a internal tls ca which is "trusted" inside of my docker swarm?
And how to setup such a internal tls proxy?

My problem is a backend which fails to authenticate a ldap user because of a self signed certificate (ldap://ldap:389) and no way to tell service to skip certificate verification and accept the self signed certificate :( 

My idea was to use "tls internal" and proxy to the ldap backend. 
1. is it possible to proxy ldap / integrate caddy l4?
2. how to trust caddy ca inside of my docker swarm?

Other way... use a public trusted LE certificate from caddy, but how to re-use LE certificate (crt, key, ca files ?!)

**Comment by francislavoie** [comment]
> is it possible to proxy ldap / integrate caddy l4?

Not currently, because CDP is Caddyfile only and caddy-l4 is JSON only.

> how to trust caddy ca inside of my docker swarm?

You'll have to add it to the trust store of each of your containers. How you do that is up to you, really. It depends which base distro you use for each image.

> Would it possible to use the caddy proxy (maybe an second instance if needed?) to create a internal tls ca

Yeah you can just use the `tls internal` and/or `acme_server` directives to set this up.

You might want to look at Smallstep tooling, it's probably more flexible for what you're trying to do. Caddy's is just a subset of Smallstep's functionality.

> Other way... use a public trusted LE certificate from caddy, but how to re-use LE certificate (crt, key, ca files ?!)

You could do that too. The certs will be in Caddy's data storage. You just need the cert and private key from there. Look in `/data` of the Caddy container.

Keep in mind that by default, Caddy has both Let's Encrypt and ZeroSSL enabled as issuers, so the cert/key might be found in one of two places depending on which one was used. Also certs are renewed roughly every 60 days (2/3 of the 90 day lifetime) so you'll need to reload anything that uses the certs externally as they get renewed.

**Comment by pwFoo** [comment]
Thanks @francislavoie,
solved my main problem and and you pointed me to some important points to note for my thoughts!
