### ISSUE TITLE
how to set fallback when web app is crashed or not loaded yet ?

### ISSUE THREAD

**Issue by beppe9000** [lucaslorentz/caddy-docker-proxy#360]
I basically want to implement something like this, to show a user-friendly error page when the upstream app/container is dead
https://caddy.community/t/how-to-have-a-reverse-proxy-fallback/13421/3

**Comment by francislavoie** [comment]
Use the `handle_errors` directive, as mentioned on that forum topic: https://caddyserver.com/docs/caddyfile/directives/handle_errors

**Comment by beppe9000** [comment]
What would the correct labels syntax be? I'm having an hard time with understanding how to translate caddyfile to labels...
```
        labels:
            caddy: mydomain.com
            caddy.reverse_proxy: "{{upstreams http 80}}"
```

**Comment by lucaslorentz** [comment]
Converting the sample from the link you shared into labesl:
```
cors / {
  origin            http://allowedSite.com
  origin            http://anotherSite.org https://anotherSite.org
  methods           POST,PUT
  allow_credentials false
  max_age           3600
  allowed_headers   X-Custom-Header,X-Foobar
  exposed_headers   X-Something-Special,SomethingElse
}
```
Can be represented with labes:
```
cors: /
cors.origin_0: http://allowedSite.com
cors.origin_1: http://anotherSite.org https://anotherSite.org
cors.methods: POST,PUT
cors.allowcredentials: false
cors.max_age: 3600
cors.allowed_headers: X-Custom-Header,X-Foobar
cors.exposed_headers: X-Something-Special,SomethingElse
```

**Comment by francislavoie** [comment]
That cors config is incorrect - that's for a plugin for Caddy v1, but it doesn't exist for Caddy v2.

For CORS in Caddy v2, just use the `header` directive https://caddyserver.com/docs/caddyfile/directives/header to set whatever CORS headers you need.

**Comment by lucaslorentz** [comment]
@francislavoie Thanks for pointing that out, I didn't notice it was a v1 config

**Comment by francislavoie** [comment]
(FWIW, the hint is that it uses `/` as a path matcher, which would never work in Caddy v2, since matchers are now exact, so that would only match requests to exactly `/` and nothing else... but also that the page linked from there is a 404 cause we removed the v1 docs from the site)

**Comment by beppe9000** [comment]
ok so if I were to add 
 `header Access-Control-Allow-Origin "https://mywebsite.com:1234"` 
to my container's labels it becomes 
 `caddy.header: "Access-Control-Allow-Origin \"https://mywebsite.com:1234\""`
 correct ?

**Comment by beppe9000** [comment]
> Use the `handle_errors` directive, as mentioned on that forum topic: https://caddyserver.com/docs/caddyfile/directives/handle_errors

From my understanding this also includes application errors. Is there a way to only match unresponsive backend errors? eg. my container crashed. and would I add it to the caddy-docker-proxy container labels to set this globally?

**Comment by francislavoie** [comment]
> to my container's labels it becomes
> `caddy.header: "Access-Control-Allow-Origin \"https://mywebsite.com:1234\""`
> correct ?

Yeah, but you don't need the double quotes in this case, you can remove them:
```yml
caddy.header: "Access-Control-Allow-Origin https://mywebsite.com:1234"
```

Only needed if you have spaces in the token value. And in that case, you can use backticks instead of double quotes, to avoid escaping: https://caddyserver.com/docs/caddyfile/concepts#tokens-and-quotes


> From my understanding this also includes application errors. Is there a way to only match unresponsive backend errors? eg. my container crashed. and would I add it to the caddy-docker-proxy container labels to set this globally? forgive me i'm not that expert with caddy yet 😄

Yeah, it would have to be in the `caddy-docker-proxy` container's labels, because otherwise the labels from your crashed container wouldn't be known/used.

I don't have a good answer for you though because there's no mechanism right now for config/labels to be "hidden" by another set of config/labels once the container starts.

@lucaslorentz WDYT about that, would it make sense to have somekind of special prefix to make a site block get only injected if no other container set the same site address? Let's say for example a label is put on the CDP container like: `caddy%: example.com` or something (I dunno, random prefix/suffix/character, TBD) then these would only apply if no other container has `caddy: example.com`, which would override it 🤔
