### ISSUE TITLE
Error during parsing: unrecognized response matcher expression

### ISSUE THREAD

**Issue by NeonFXFusion** [lucaslorentz/caddy-docker-proxy#376]
I have no clue why this is happening and I cant seem to find any similar errors reported on caddy forums, stack overflow or github.

Generated relevant config:
```
(cors) {
	@error expression {http.error.status_code} == 502
	handle_response @error {
		respond \"Errm... this is awkward...\"
	}
	header_up Origin
	header_up X-Real-IP {remote_host}
	header_down -X-Powered-By
	header_down -Server
	header_down Access-Control-Allow-Origin {args.0}
	header_down Access-Control-Allow-Credentials true
	header_down Access-Control-Allow-Methods OPTIONS,HEAD,GET,POST,PUT,PATCH,DELETE
}
```

Error reported by caddy-proxy container (cleaned up):
```
Removing invalid block: parsing caddyfile tokens for 'reverse_proxy': Caddyfile:6 - Error during parsing: unrecognized response matcher expression
subdomain.example.com {
	reverse_proxy 10.0.5.26:80 {
		import cors https://subdomain.example.com
	}
}
```
Relavant documentation: https://caddyserver.com/docs/caddyfile/matchers#expression

**Comment by lucaslorentz** [comment]
CDP validates each site config and automatically removes the invalid ones. That way a broken service won't affect a functional one.

Looks like CDP converted your labels properly, as the config that was removed looks good:
```
subdomain.example.com {
	reverse_proxy 10.0.5.26:80 {
		import cors https://subdomain.example.com
	}
}
```

Looks like Caddy also executed the import properly, and found (cors) snippet, because the error is specifically about the response matcher that is inside the snippet.

Can you please try adding quotes to your expression `{http.error.status_code} == 502`. There is an example in this page with quotes: https://caddyserver.com/docs/caddyfile/directives/handle_errors

**Comment by lucaslorentz** [comment]
Alternatively, it could be that either expression is not supported in the response matcher. @francislavoie might know if that
