### ISSUE TITLE
CDP and caddy-gen

### ISSUE THREAD

**Issue by woss** [lucaslorentz/caddy-docker-proxy#388]
Today i found out the [caddy-gen](https://github.com/wemake-services/caddy-gen) project, was wondering how this compares to it.

Any obvious benefits of using the CDP vs caddy-gen and vice-versa?

Thank you,

**Comment by lucaslorentz** [comment]
I will try to do a comparison, but I'm not very familiar with caddy-gen.

### How you configure your Caddyfile

**CDP** focus on a convention to express a caddyfile using docker labels.
- You need to configure more labels. Almost every line of a caddyfile needs a label for it.
- Docker labels have full control of the Caddyfile and by reading labels you know how the final Caddyfile will be.
- You only need to maintain docker labels.
- You need knowledge about Caddy and Caddyfile concepts to write your labels.

I think this approach is more suitable if you trust who defines labels in your docker resources and wants them to have full control over caddy.

**Caddy-gen** focus on string templates that uses docker labels as input.
- You need to configure fewer labels. Templates can make decisions and render big chunks based on a single label.
- Docker labels have limited control of the Caddyfile and you need to know how the template uses the labels to know how the final Caddyfile will be.
- In the default template is not enough for you, you would need to maintain labels and templates 
- You need less knowledge about caddy to write labels. But you need the knowledge to write templates.

I think this approach is more suitable if you want caddy experts to define templates and which labels it will support, while other people set those labels in docker resources.

### Error tolerance

**CDP** [process](https://github.com/lucaslorentz/caddy-docker-proxy/blob/master/caddyfile/processor.go) your caddyfile and remove misconfigured/unparseable Caddyfile sections. This reduces the impact a single misconfigured container can do.  If you missconfigure one site, it will be removed from the final Caddyfile and not served, while all other sites will continue being served. This also allows correct configurations to continue evolving and being applied, instead of blocking all Caddyfile updates because of a single problematic site. This behavior can be disabled via a flag.

I don't know how **Caddy-gen** would behave if you write some invalid directives inside the label **virtual.host.directives** for example.

### Server/controller separation (relevant for docker swarm)

If you don't want a single point of failure, you should have multiple replicas of your caddy proxy container running, preferably on different docker hosts.

Both **CDP** and **caddy-gen** support that scenario if you configure it to run only on manager nodes. Each caddy instance will individually connect to docker API, read swarm objects, generate its own Caddyfile and serve traffic. Caddy replicas can even orchestrate and solve ACME challenges if they share the volume.

**CDP** supports a different approach as well: You can run a single replica of **CDP controller** and multiple replicas of **CDP server**. The **CDP** controller connects to docker API, reads swarm objects, generates a Caddyfile then pushes the same Caddyfile to all replicas of **CDP servers**, which in turn serves traffic. The advantages are:
- Caddyfile is not redundantly generated by all replicas
- Better cluster resources utilization because only **CDP controller** needs access to Docker API, therefore only the **CDP controller** needs to run on manager nodes, and all **CDP servers** can run on worker nodes.

### Maturity/stability

To be honest, I'm not dogfooding CDP for quite some time. I'm maintaining Kubernetes clusters with Istio.

The last time I run **CDP** was years ago, It was a small cluster of up to 5 docker hosts. It was quite stable, but eventually, a caddy instance had temporary connection issues to some containers. Caddy config was good, it seemed to be a Docker Swarm problem. I mitigated that issue by configuring health checks in Caddy reverse proxies, so it could skip the temporarily unreachable containers.

I don't know how many members of our community are running **CDP** on critical prod systems. Maybe we should start an issue to gather more insights about that.

Can't comment about **caddy-gen**. Maybe just that "docker-gen" seems to be battle-tested.

**Comment by woss** [comment]
Hey @lucaslorentz, honestly, i didn't expect this kind of answer, the quality of the content and clear explanation blew my mind off. THIS is the true response from the Open Source maintainer!!! 👏 

I use the CDP in production for a few services without the swarm, and I like it.  It seems that the caddy-gen follows a very similar path as the jwilders' nginx-proxy. 

Once again, thank you for your time and effort, i got my answer, which is: `I'm sticking with CDP`.

🥳
