### ISSUE TITLE
Issues with Network host mode and SearxNG 

### ISSUE THREAD

**Issue by ghost** [lucaslorentz/caddy-docker-proxy#392]
Hi, I'm self hosting a searxng instance using their docker file. However, using their default docker-compose.yaml file I get a "tcp 127.0.0.1:8080 already in use" error. They set "network_mode = host" as default for caddy. If I remove this line the instance starts but am not an expert and I don't really understand why I should let caddy connect to the host in this case and what is the difference if I simply let docker create a default network for caddy. Any help would be greatly appreciated thanks.

**Comment by lucaslorentz** [comment]
Host network means that the container will use host network interface.
You probably have either another container running in host network mode and using port 8080, or you have some non docker process using port 8080.
By removing that line, a virtual network interface is created for the container, and no conflicts would happen because only your container will be using that interface.
