### ISSUE TITLE
Could I specify an external TLS certificate?

### ISSUE THREAD

**Issue by 2ndMessiah** [lucaslorentz/caddy-docker-proxy#436]
I think it's possible because I used them on the normal version of Caddy. However, I do not really know how to set this in the compose yaml.

Please give your advice. Appreciate it!

**Comment by IndeedNotJames** [comment]
First, you would have to make the external TLS certificate available from within the Docker container.

The most straight forward way is to add another volume/bind mount containing your certificate:

```
volumes:
  - ./certificate:/certificate
```

and then just add another label named `caddy.tls` to your upstream container containing the paths as value.
Assuming your local directory `./certificate` contains the two files `cert.pem` and `key.pem`, use:
```
labels:
  caddy.tls: "/certificate/cert.pem /certificate/key.pem
``` 


Because remember, all those labels get converted to one Caddyfile, as explained in https://github.com/lucaslorentz/caddy-docker-proxy#labels-to-caddyfile-conversion

So the syntax and all the directive are the same :)
In this case, https://caddyserver.com/docs/caddyfile/directives/tls#examples

**Comment by 2ndMessiah** [comment]
> First, you would have to make the external TLS certificate available from within the Docker container.
> 
> The most straight forward way is to add another volume/bind mount containing your certificate:
> 
> ```
> volumes:
>   - ./certificate:/certificate
> ```
> 
> and then just add another label named `caddy.tls` to your upstream container containing the paths as value. Assuming your local directory `./certificate` contains the two files `cert.pem` and `key.pem`, use:
> 
> ```
> labels:
>   caddy.tls: "/certificate/cert.pem /certificate/key.pem
> ```
> 
> Because remember, all those labels get converted to one Caddyfile, as explained in https://github.com/lucaslorentz/caddy-docker-proxy#labels-to-caddyfile-conversion
> 
> So the syntax and all the directive are the same :) In this case, https://caddyserver.com/docs/caddyfile/directives/tls#examples

thx!!!
