### ISSUE TITLE
Connection not private error

### ISSUE THREAD

**Issue by MichaelAntonFischer** [lucaslorentz/caddy-docker-proxy#463]
Hi,

thanks for providing this great tool. Unfortunately it seems the certificates are not correctly generated, since every browser gives me an error that the connection is not private and the docker container tells me:

"Warning: \"certutil\" is not available, install \"certutil\" with \"apt install libnss3-tools\" or \"yum install nss-tools\" and try again"}

**Comment by IndeedNotJames** [comment]
Are you using `caddy.tls: internal` by chance?
Those certificates are what most other tools would call _self-signed_.

Please refer to the Caddyfile documentation for the `tls` directive at https://caddyserver.com/docs/caddyfile/directives/tls

**Comment by MichaelAntonFischer** [comment]
Hi,

yes, I do. Thanks for the quick reply. On another server where I use standard Caddy Docker build with manual caddy file, I also use internal and it works. According to Caddy docs it shouldn't be necessary to change. It seems to me that nss-tools is just missing from the build.

**Comment by MichaelAntonFischer** [comment]
Btw I tried to add it to the build, but I failed building from this repo and just using the docker image doesn't work, since the build deletes almost everything from apline image, leaving it without ability to handle RUN apk add command

**Comment by IndeedNotJames** [comment]
It depends on what you are trying to archive :)

Certificates issued using tls internal are not signed by publically trusted CAs and thus will be flagged as "insecure" by browsers and other programs.

If you don't intent on making your websites public or expect all your visitors will click through those scary and off-turning prompts, then feel free to continue using them.

I can only really guess why your other server works just fine with `tls internal`.
There are a lot of factors, and you didn't share all that much info to begin with :^) 

The automatic trust install error/warning you shared shouldn't really matter, as this would just install the internal Caddy CA into your Docker container, not your actual system

**Comment by francislavoie** [comment]
> The automatic trust install error/warning you shared shouldn't really matter, as this would just install the internal Caddy CA into your Docker container, not your actual system

Yeah. To clarify, this was just a warning (not an error) about one particular approach to _installing_ the cert to the system's (the container's) trust store. It's not a problem with generating the certificate. This is normal behaviour.

If you're using a cert issued by Caddy's internal CA, then it's also normal to see errors in your browser if you haven't installed the CA's root cert into your host's browser or system's trust store. You can get the root CA cert from the container's `/data` volume and install it manually if you want.

But like @IndeedNotJames said, a publicly trusted cert is in general much easier to manage since it can be fully automated and involves no manual installation steps, with wider compatibility (any device would trust it).

**Comment by MichaelAntonFischer** [comment]
Can you please clarify on the "publicly trusted certificate" from caddy's doc my understanding was that internal certificate is the way you should go and that (if DNS is set correctly) it should generate publicly trusted certificates.

**Comment by francislavoie** [comment]
Publicly trusted means trusted by a CA like Let's Encrypt or ZeroSSL which have their root CA cert already installed in the trust stores of almost all devices in the world. Using Caddy's internal CA means that only devices that you install Caddy's root CA cert on will trust it. By default, that's none (obviously) because the CA doesn't exist until you run Caddy with the `tls internal` option.
