### ISSUE TITLE
[question] using public domain for local domain https

### ISSUE THREAD

**Issue by zilexa** [lucaslorentz/caddy-docker-proxy#476]
I have a question after reading this reply: 
https://github.com/lucaslorentz/caddy-docker-proxy/issues/462#issuecomment-1434003375

> Better yet though, get a public domain like from DuckDNS, then you don't need to mess with setting up a DNS server. You can use your LAN IP address with that domain too. To get a publicly trusted cert, you can use the github.com/caddy-dns/duckdns plugin to use the ACME DNS challenge. That way your browser won't complain about untrusted certificates.

I have a public domain and have 4 services in my compose that are reverse proxied already with caddy-docker-proxy and several other services that use local domain such as http://vpnui.o, http://adguard.o, http://dash.o. 
I use Adguard Home as well, with its DNS rewrite option to ensure all these ...o domains redirect to my local server host IP. 

If I simply add: 
```
caddy_tls: internal
```
to each of them in my Compose, I even get https for these domains, but every browser will give the scary warning the connection is unsafe (I can still proceed though). 

I didn't know I could use my public domain for a local domain as well. It is a bit unclear to me what you mean by this. Isn't a certificate linked to a domain? So I cannot use the certificate for mypublicdomain.cloud for local domain adguard.o ?

I tried to find Caddyfile examples online, but couldn't find any. 
Do you mean I should manually download the cert files from my domain provider and put them on every device? Or somewhere in a mapped volume of the caddy container?

**Comment by francislavoie** [comment]
The label should be `caddy.tls: internal`.

> I even get https for these domains, but every browser will give the scary warning the connection is unsafe

Yep, because that's asking Caddy to sign the certs with its internal CA, which is not publicly trusted.

See the docs here https://caddyserver.com/docs/running#usage we have an explanation of how to install the root CA cert on the host machine with a single command. You can copy the root CA cert to your other devices in your LAN if necessary. Keep in mind that many browsers have their own trust stores, so you may need to install the cert in those trust stores as well.

> I didn't know I could use my public domain for a local domain as well.

Well, a domain is just a name that resolves to an IP address. The IP address you use doesn't need to be a WAN IP, it could be a LAN IP like `192.168.1.10` or something. E.g. you could resolve `your.duckdns.org` to your LAN IP. A "public" DNS name, but a "private" IP address.

But that would mean that you could not use a public TLS cert with the ACME HTTP or TLS-ALPN challenges because the ACME issuers would not be able to reach your server with that LAN IP address. So your options are either `tls internal` or the DNS challenge instead.

**Comment by zilexa** [comment]
@francislavoie thank you for your quick and extensive reply. I do not fully understand it. I am def no expert here. 

The way I understand it: 
- `tls internal` with root CA cert copied to each device --> this is not a practical solution for me.
- "the DNS challenge"  but your message only seems to mention this at the bottom. Is this what I am originally asking about what this means, how to do this? 

I am grateful for your reply, but it seems my question is not answered.. you refer to something at the bottom that I actually asked about by referring to an old comment. 

If you could give me a few pointers, considering I do have a public domain for my homeserver already (via porkbun) and would like to understand how to use this DNS challenge to get a proper https for local domains.

**Comment by francislavoie** [comment]
See https://caddy.community/t/how-to-use-dns-provider-modules-in-caddy-2/8148 re DNS challenge, it explains what you need to know.

**Comment by francislavoie** [comment]
Yes you can definitely use the DNS challenge with CDP. You just need to make a Docker image which includes a plugin for your DNS provider to solve the challenges. See the CDP README which has an example Dockerfile for building with additional plugins.
