### ISSUE TITLE
Server Logs Permissions

### ISSUE THREAD

**Issue by StoryHack** [lucaslorentz/caddy-docker-proxy#501]
I'm writing a simple script to process json-fomatted log files generated by caddy-docker-proxy. When I add a new site via a docker-compose.yml file, I use a bind mount and correct caddy labels to write out the log files.

For example, the yml for caddy-docker-proxy, I bind:

`...
    volumes:
      -./logs:/logs:z

`

Then, in the section for the actual server, I have

`...
    labels:
      caddy: simple.local
      caddy.reverse_proxy: "{{upstreams}}"
      caddy.log:
      caddy.log.output: file /logs/simple.local/access.log
      caddy.log.output.roll_size: 10mb
      caddy.log.output.roll_keep: 5
      caddy.log.output.roll_uncompressed:
      caddy.log.output.roll_keep_for: 720h
      caddy.log.format: json
`

Then, I have another container which runs the script that actually processes the log files. In this I bind mount to the same local ./logs directory.

caddy writes and rolls over the log files just fine.

However, the script in the new container gets a permissions error when I try to read in the logs JSON-formatted  log file. looking in the directory, the log file is created by caddy's root user with restricted permissions (either 600 or 700, I can't remember offhand). I can go in after and change permissions so that the container with the script can read the log. But I don't want to have to manually change permissions of those logs. 

Is there any setting or label to tell caddy to write those log files with world "read" permissions?

**Comment by francislavoie** [comment]
Your comment formatting is a bit messed up. Use triple backticks on their own line for markdown code blocks, not single backticks (which are meant to be used for inline code `like this` and not for multi-line blocks).

> Is there any setting or label to tell caddy to write those log files with world "read" permissions?

If you initially create the log file with the permissions you want, it should retain those permissions. But customizing it for new logs is not supported because the lib that Caddy uses, Lumberjack, doesn't support it (yet). See https://github.com/natefinch/lumberjack/pull/168. That lib is unfortunately no longer being maintained, so we're hoping someone with time on their hands to fork it and make various improvements. We don't really have time ourselves to maintain another library.

Either way, this repo is the wrong place for this, since this is more of a question for Caddy specifically, not CDP.

**Comment by StoryHack** [comment]
Sorry on the formatting. Thanks on the answer.
