### ISSUE TITLE
Should we change docker/docker to moby/moby

### ISSUE THREAD

**Issue by ibnesayeed** [lucaslorentz/caddy-docker-proxy#6]
https://github.com/lucaslorentz/caddy-docker-proxy/blob/ab90ea6d7ea2d2209663c77f3736982a391bed57/plugin/generator.go#L12-L14

A while ago, docker decided to rename their repositories and rebrand a few things under `moby`. While GitHub has redirects in place to maintain backward compatibility, I think we might want to update the code to reference new location by replacing `docker/docker` to `moby/moby`.

**Comment by lucaslorentz** [comment]
Nice catch! I will update and run some tests.

**Comment by ibnesayeed** [comment]
I did no check all the files, but there might be other places where the older path is used in imports.

**Comment by lucaslorentz** [comment]
Tried to update it, but build fails. I think because it mixes with references to old docker/docker inside dependencies and also inside moby.

The good thing is that docker/docker still points to up to date code. I downloaded a build from Caddy Download page used Docker API version 1.37, which is quite new.

I will try again to move to moby/moby later.

**Comment by jakebailey** [comment]
docker/* is still the canonical import path for all of the Docker-related code, even the stuff that lives in the  moby account. If you look at any of the Docker libs, you'll see they specify the import path with an import comment at the top of their files. See moby/moby#36194.

**Comment by ibnesayeed** [comment]
Thanks @jakebailey for this info. I was not aware of the canonical import annotation. This explains why the builds would fail when `moby/moby` is used. I think this ticket can be closed now.
