### ISSUE TITLE
Using CDP as a reverse proxy for non-docker services - is it possible?

### ISSUE THREAD

**Issue by AlexPewMaster** [lucaslorentz/caddy-docker-proxy#640]
Hi, I would like to use this as my reverse proxy. I have many Docker containers running on the same machine that's also running a reverse proxy, but I also have a tunnel for other services that run on a different machine. Is there a way that I can configure parts of CDP to proxy some things to `localhost` without a Docker container to attach the labels to?

**Comment by francislavoie** [comment]
Yes it's possible. You can either put labels right on your CDP container itself, or provide a base Caddyfile (see env config options).

It wouldn't be `localhost` though, because localhost means "connect to this same container". Containers are isolated from the host. You would connect to `host.docker.internal` instead (Google it for more details).

**Comment by ksurl** [comment]
you can use a placeholder container with labels to point to an external host ip. a lightweight option could be a busybox container with no networking and set to run tail -f /dev/null to stay running.
