### ISSUE TITLE
[FR]merge the same caddy.address from different containers

### ISSUE THREAD

**Issue by renothing** [lucaslorentz/caddy-docker-proxy#65]
for example, there is an application based php+mysql like wordpress. It will create two container, one for static files, another for php backend, both of them use  the same domain.  if we use caddy docker plugin, it will report duplicate error. because two container have the same label "caddy.address".

**Comment by lucaslorentz** [comment]
Can you please write how the final caddyfile should look like after merging?

That looks like 2 proxies to different containers.

Em 9 de set de 2018 4:24 PM, renothing <notifications@github.com> escreveu:

for example, there is an application based php+mysql like wordpress. It will create two container, one for static files, another for php backend, both of them use the same domain. if we use caddy docker plugin, it will report duplicate error. because two container have the same label "caddy.address".

**Comment by renothing** [comment]
for example, this is my application with caddy
```
www.example.com {
  tls {
    dns cloudflare
  }
  root /var/static
  fastcgi / 172.17.0.3:9000 php {
    root /var/www
    index index.php
    ext .php
  }
}
```
if I use docker, I will create two containers, one for static, another for php. and both of them use the same domain.

how would I set labels in caddy-docker ? especially fastcgi endpoint  like `127.17.0.3:9000`

**Comment by francislavoie** [comment]
This should be resolved by Caddy v2. Closing.
