### ISSUE TITLE
Sensitive information exposed

### ISSUE THREAD

**Issue by VDenisyuk** [lucaslorentz/caddy-docker-proxy#664]
Hello community,

I just want to ask if you consider this normal, that security tokens (and probably other sensitive information), stored and provided via `env`, are then openly exposed in logs with default `info` log level (see `dns` directive)?

`{"caddyfile":"*.example.com {\n\t@dozzle {\n\t\thost dozzle.example.com\n\t}\n\t@whoami1 {\n\t\thost whoami1.example.com\n\t}\n\t@whoami2 {\n\t\thost whoami2.example.com\n\t}\n\treverse_proxy @dozzle dozzle:8080 {\n\t\tflush_interval -1\n\t}\n\treverse_proxy @whoami1 whoami1:80\n\treverse_proxy @whoami2 whoami2:80\n\ttls {\n\t\t**dns cloudflare fully_exposed_security_token_here**\n\t\tresolvers 1.1.1.1\n\t}\n}\n","level":"info","logger":"docker-proxy","msg":"New Caddyfile","ts":1727350535.3434057}`

**Comment by candrewlee14** [comment]
You should use `{env.CF_TOKEN}` instead of $CF_TOKEN. This will be replaced at runtime and not put in the logs.

**Comment by VDenisyuk** [comment]
Ah, good to know. Thank you!

**Comment by polarathene** [comment]
Just as additional context, in a `compose.yaml` file there is variable interpolation so `{$ENV_HERE}` would be resolved by Docker Compose before any Caddyfile config was generated from labels by CDP.

If you do need the Caddyfile to be generated with the ENV instead of querying it at runtime whenever accessed (_the `{env.ENV_HERE}` placeholder_), which is useful for non-sensitive inputs, you can do so with `{$$ENV_HERE}`, where the extra `$` escapes `$`, thus opt-outs of the variable interpolation feature of Compose and your Caddyfile will have `{$ENV_HERE}` 👍
